# Generated by Django 4.0.3 on 2022-03-29 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirm_message',
            options={'ordering': ['-created_time'], 'verbose_name': 'Verification code', 'verbose_name_plural': 'Verification code'},
        ),
        migrations.RemoveField(
            model_name='confirm_message',
            name='c_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AddField(
            model_name='confirm_message',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
