# Generated by Django 4.0.3 on 2022-03-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_confirm_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm_message',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
